import "../styles/globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import { PlayerContextProvider } from "./context/player";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ThirteenScore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="winter" lang="en">
      <body>
        <Navbar />
        <PlayerContextProvider>{children}</PlayerContextProvider>
      </body>
    </html>
  );
}
